# fly.toml app configuration file generated for marches on 2026-07-02T16:44:41-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'marches'
primary_region = 'lax'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  memory_mb = 256
